import { createAsyncThunk } from '@reduxjs/toolkit';
import { employeeService } from '@/features/employees/services/employeeService';
import { Employee } from '@/features/employees/types';
import { parseApiError } from '@/lib/utils';

/**
 * Async thunk to fetch all employees from the API
 * @returns {Promise<Employee[]>} Array of employee objects
 * @throws {string} Error message if request fails
 */
export const fetchEmployees = createAsyncThunk(
  'employees/fetchAll',
  async (_, { rejectWithValue }) => {
    try {
      const response = await employeeService.getAll();
      return response.data;
    } catch (error) {
      const parsedError = parseApiError(error);
      return rejectWithValue(parsedError || 'Failed to fetch employees');
    }
  }
);

/**
 * Async thunk to add a new employee
 * @param {Omit<Employee, 'id'>} employee - Employee data without id (generated by server)
 * @returns {Promise<Employee>} Created employee object with id
 * @throws {string} Error message if creation fails
 */
export const addEmployee = createAsyncThunk(
  'employees/add',
  async (employee: Omit<Employee, 'id'>, { rejectWithValue }) => {
    try {
      const response = await employeeService.create(employee);
      return response.data;
    } catch (error) {
      const parsedError = parseApiError(error);
      return rejectWithValue(parsedError || 'Failed to add employee');
    }
  }
);

/**
 * Async thunk to update an existing employee
 * @param {Object} params - Update parameters
 * @param {number} params.id - ID of employee to update
 * @param {Partial<Employee>} params.data - Partial employee data to update
 * @returns {Promise<Employee>} Updated employee object
 * @throws {string} Error message if update fails
 */
export const updateEmployee = createAsyncThunk(
  'employees/update',
  async ({ id, data }: { id: number; data: Partial<Employee> }, { rejectWithValue }) => {
    try {
      const response = await employeeService.update(id, data);
      return response.data;
    } catch (error) {
      const parsedError = parseApiError(error);
      return rejectWithValue(parsedError|| 'Failed to update employee');
    }
  }
);

/**
 * Async thunk to delete an employee
 * @param {number} id - ID of employee to delete
 * @returns {Promise<number>} ID of deleted employee for state update
 * @throws {string} Error message if deletion fails
 */
export const deleteEmployee = createAsyncThunk(
  'employees/delete',
  async (id: number, { rejectWithValue }) => {
    try {
      await employeeService.delete(id);
      return id;
    } catch (error) {
      const parsedError = parseApiError(error);
      return rejectWithValue(parsedError || 'Failed to delete employee');
    }
  }
);